# Generated by Django 4.0.5 on 2022-06-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=64)),
                ('descripcion', models.TextField(max_length=512)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
