# Generated by Django 4.0.5 on 2022-06-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
