# Generated by Django 4.0.5 on 2022-06-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_mascota_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='mascota',
        ),
        migrations.AddField(
            model_name='categoria',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='productos.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='static/productos/'),
        ),
    ]
