# Generated by Django 4.0.5 on 2022-06-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categoria_mascota_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default='', max_length=512),
        ),
    ]
