# Generated by Django 4.0.5 on 2022-06-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/categorias/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/productos/'),
        ),
    ]
